Ceturtais majasdarbs iesniegts
siviars/home-exercises-05-2022 pull request #4
Opened 2022-10-02 19:47 UTC by siviars

2022-11-14 17:15 UTC, NilsKula requested changes

2022-11-14 17:15 UTC, NilsKula commented on src/io/codelex/dateandtime/practice/DatePeriod.java
> +    LocalDate start, startResult;
private un katru varaible savā rindā

2022-11-14 17:15 UTC, NilsKula commented on src/io/codelex/dateandtime/practice/DatePeriod.java
> +    public boolean checkPeriod(DatePeriod name) {
private

2022-11-14 17:15 UTC, NilsKula commented on src/io/codelex/dateandtime/practice/Exercise1.java
> +        int workHours = (int) (firstDate.datesUntil(secondDate).filter(day->day.getDayOfWeek().getValue()<=5).count()*8);
formatting, use spaces

8 - constant

2022-11-14 17:15 UTC, NilsKula commented on src/io/codelex/oop/Exercise9_10/Cone.java
> +package io.codelex.oop.Exercise9_10;
package ar mazo burtu un bez underscore

2022-11-14 17:15 UTC, NilsKula commented on src/io/codelex/oop/Exercise9_10/Cone.java
> +    double height;
private

2022-11-14 17:15 UTC, NilsKula commented on src/io/codelex/oop/cars/Car.java
> +    public Car(String name, String model, EngineType engineType, int price, int year, Manufacturer manufacturers) {
manufacturer jāpadod kā list

2022-11-14 17:15 UTC, NilsKula commented on src/io/codelex/oop/cars/Car.java
> +        return price == car.price && year == car.year && Objects.equals(name, car.name) && Objects.equals(model, car.model) && Objects.equals(engineType, car.engineType) && Objects.equals(manufacture
atdali uz jaunām rindām, lai neiet ārā no ekrāna

2022-11-14 17:15 UTC, NilsKula commented on src/io/codelex/oop/cars/CarService.java
> +    public void sortByEngine(EngineType engine) {
:+1: labi ka generic

2022-11-14 17:15 UTC, NilsKula commented on src/io/codelex/oop/parcels/Parcel.java
> +        if (xLength >= 30 && yLength >= 30 && zLength >= 30) {
max parametrus definē kā konstantes

2022-11-14 17:15 UTC, NilsKula commented on src/io/codelex/oop/persons/Person.java
> +    public String firstName;
private

2022-11-21 13:38 UTC, siviars commented on src/io/codelex/dateandtime/practice/DatePeriod.java
> +    LocalDate start, startResult;
Saliku private un variables katru savā rindā.

2022-11-21 13:39 UTC, siviars commented on src/io/codelex/dateandtime/practice/DatePeriod.java
> +    public boolean checkPeriod(DatePeriod name) {
Saliku private

2022-11-21 13:39 UTC, siviars commented on src/io/codelex/dateandtime/practice/Exercise1.java
> +        int workHours = (int) (firstDate.datesUntil(secondDate).filter(day->day.getDayOfWeek().getValue()<=5).count()*8);
Noformatēju un sataisīju konstanti.

2022-11-21 13:39 UTC, siviars commented on src/io/codelex/oop/Exercise9_10/Cone.java
> +package io.codelex.oop.Exercise9_10;
Izlaboju nosaukumu.

2022-11-21 13:40 UTC, siviars commented on src/io/codelex/oop/Exercise9_10/Cone.java
> +    double height;
Saliku private.

2022-11-21 13:42 UTC, siviars commented on src/io/codelex/oop/cars/Car.java
> +    public Car(String name, String model, EngineType engineType, int price, int year, Manufacturer manufacturers) {
Cik es saprotu vienai mašīnai var būt tikai viens ražotājs. Tāpēc konstruktorā pieprasu ražotāju. Bet zemāk pievienoju ražotāju kopējam sarakstam.

2022-11-21 13:42 UTC, siviars commented on src/io/codelex/oop/cars/Car.java
> +        return price == car.price && year == car.year && Objects.equals(name, car.name) && Objects.equals(model, car.model) && Objects.equals(engineType, car.engineType) && Objects.equals(manufacture
Atdalīju uz jaunām rindām.

2022-11-21 13:44 UTC, siviars commented on src/io/codelex/oop/parcels/Parcel.java
> +        if (xLength >= 30 && yLength >= 30 && zLength >= 30) {
Vairāk lietotos parametrus aizstāju ar konstanti.

2022-11-21 13:45 UTC, siviars commented on src/io/codelex/oop/persons/Person.java
> +    public String firstName;
Saliku private.

2022-11-22 14:33 UTC, NilsKula commented on src/io/codelex/oop/cars/Car.java
> +    public Car(String name, String model, EngineType engineType, int price, int year, Manufacturer manufacturers) {
tā kā tas ir list iekš `car` tad sanāk ka var būt vairāki vienai mašīnai
biški kaut kā confusing :smile:

2022-11-22 14:33 UTC, NilsKula approved these changes

2022-11-27 18:58 UTC, merged